### ISSUE TITLE
Command user-friendliness proposal

### ISSUE THREAD

**Issue by eheimer** [JimiIT92/UniverseGuardAPI7#1]
While I was waiting for the API7 version to be released, I was toying around with using the Nations plugin for world-guarding.  UniverseGuard has a lot more features that I'm looking for, so I'm going to make the switch.  However, from using Nations for awhile, I really became accustomed to their super-easy user interface for using their commands.  

- [TAB] completes all of the command parameters, or pops up a list of matches if there's more than one.
- When displaying all of the permissions info (flags) for a region, the nodes are clickable links to issue the respective command to toggle them on/off.

This prevents a LOT of repetitive typing and makes the commands a lot more intuitive.

I'm a developer in my other life, so if this is a feature you would like implemented and want me to take a stab at it, I'd love to help out.  I've never contributed to a git project before, so give me some hints on how to get started.

-Eric

**Comment by JimiIT92** [comment]
Thank you for using my plugin and for your suggestions :) Tab completition is one of the feature i'm trying to work on from such a long time and i totally agree it should be added soon ;) For the clickable flags, that's another thing i agree could be very useful and has already been suggested. Unfortunately these are things i've never tried to do in Sponge, so it will take some time to get them work. Also, if you really want to give your help and contribution to this project than you are welcome of course, the more brains we are the more and better things we can do ;)

**Comment by eheimer** [comment]
I've got the tab completion figured out.  It might take me a couple days to wrap up all of the commands.

**Comment by Brycey92** [comment]
Submit a PR when you have tab completion ready, and we'll take a look at it. After that, if you plan to implement clickable links, you may want to wait until we merge your first PR so as to prevent merge conflicts or too-large PRs.

**Comment by JimiIT92** [comment]
Really glad to hear that, if you want some help feel free to ask :)

**Comment by eheimer** [comment]
issue #3 opened for the clickable flag output, so closing this issue.
