### ISSUE TITLE
changes to default config file get overwritten with each restart

### ISSUE THREAD

**Issue by eheimer** [JimiIT92/UniverseGuardAPI7#4]
I've seen what's causing this, a simple fix in the UniverseGuard.java file.  See the `if` statement in the `loadConfig()` method.  

I can knock this one out as soon as I have a free minute.

**Comment by JimiIT92** [comment]
Ok, then i'll wait for the fix in order to avoid some conflicts :)

**Comment by eheimer** [comment]
I won't get to this for another 3 or 4 hours, so I won't feel bad if you take it.  :)

**Comment by JimiIT92** [comment]
Ok, i'll see if i can figure it out :)

**Comment by JimiIT92** [comment]
I don't know what's causing it, i've tried to change the config file in localhost then restart the server and file wasn't changed, my edits were still there :/

**Comment by eheimer** [comment]
Hmmm, maybe it was a fluke when I tried it.  It looked to me like the code was reloading the default config every time, regardless of whether the file already exists, but maybe I misread it.  Maybe it was because I tried creating a new node.  I can do some more testing, but if you weren't able to reproduce it, it's probably not a big deal.

**Comment by JimiIT92** [comment]
If you add a new node to the config that will be deleted on the next reload, that's true. But that's to avoid some wrong configurations. If you are going to add a new node to config something than you have to update the functions to get the values so it gets that and it doesn't get overwritten

**Comment by eheimer** [comment]
Fair enough.  That's probably what it was that I noticed then.
